version: '3.9'
services:
  web_application:
    image: application
    build:
      context: .
      dockerfile: ContactsCounterparties/Dockerfile
    container_name: web_application
    ports:
      - '5000:80'
  sql:
    image: 'mcr.microsoft.com/mssql/server:2022-latest'
    container_name: mssql
    ports:
      - '1433:1433'
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=PaSSw0rdW_w
    volumes:
      - ./create-db.sql:/scripts/
    command:
      - /bin/bash
      - -c
      - |
        # Launch MSSQL and send to background
        /opt/mssql/bin/sqlservr &
        # Wait 30 seconds for it to be available
        # (lame, I know, but there's no nc available to start prodding network ports)
        sleep 30
        # Run every script in /scripts
        # TODO set a flag so that this is only done once on creation, 
        #      and not every time the container runs
        for foo in /scripts/*.sql
          do /opt/mssql-tools/bin/sqlcmd -U sa -P $$SA_PASSWORD -l 30 -e -i $$foo
        done
        # So that the container doesn't shut down, sleep this thread
        sleep infinity